version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn clean package -DskipTests=true
artifacts:
  files:
    - target/myweb-0.15.0.war
  discard-paths: yes
