version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn clean package -DskipTests=true
  post_build:
    commands:
      - mv target/myweb*.war target/myweb.war
artifacts:
  files:
    - target/myweb*.war
  discard-paths: yes
